# Generated by Django 5.2.7 on 2025-11-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='Обложка курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='course_icons/', verbose_name='Иконка курса'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/', verbose_name='Фото ментора'),
        ),
    ]
