# Generated by Django 5.2.7 on 2026-05-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_cover_image_course_icon_mentor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_student_kpi', models.FloatField(default=0.0)),
                ('avg_attendance', models.FloatField(default=0.0)),
                ('homework_completion_rate', models.FloatField(default=0.0)),
                ('total_kpi', models.FloatField(default=0.0)),
                ('students_count', models.IntegerField(default=0)),
                ('courses_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi', to='education.mentor')),
            ],
            options={
                'verbose_name': 'KPI тренера',
                'verbose_name_plural': 'KPI тренеров',
            },
        ),
        migrations.CreateModel(
            name='StudentKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_score', models.FloatField(default=0.0)),
                ('homework_score', models.FloatField(default=0.0)),
                ('grade_score', models.FloatField(default=0.0)),
                ('total_kpi', models.FloatField(default=0.0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('attended_lessons', models.IntegerField(default=0)),
                ('total_homeworks', models.IntegerField(default=0)),
                ('submitted_homeworks', models.IntegerField(default=0)),
                ('grades_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi', to='education.student')),
            ],
            options={
                'verbose_name': 'KPI ученика',
                'verbose_name_plural': 'KPI учеников',
            },
        ),
    ]
